// World Cities Data
import { WorldCity } from '../types';

// Default starting cities
export const WORLD_CITIES: WorldCity[] = [
  { id: 'helsinki', name: 'Helsinki', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'london', name: 'London', region: 'UK', timezone: 'Europe/London' },
  { id: 'paris', name: 'Paris', region: 'France', timezone: 'Europe/Paris' },
  { id: 'nyc', name: 'New York', region: 'USA', timezone: 'America/New_York' },
  { id: 'la', name: 'Los Angeles', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'tokyo', name: 'Tokyo', region: 'Japan', timezone: 'Asia/Tokyo' },
  { id: 'sydney', name: 'Sydney', region: 'Australia', timezone: 'Australia/Sydney' },
  { id: 'dubai', name: 'Dubai', region: 'UAE', timezone: 'Asia/Dubai' },
  { id: 'singapore', name: 'Singapore', region: 'Singapore', timezone: 'Asia/Singapore' },
];

// Expanded pool for adding cities
export const ALL_CITIES: WorldCity[] = [
  // --- NORDICS & FINLAND ---
  { id: 'helsinki', name: 'Helsinki', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'tampere', name: 'Tampere', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'turku', name: 'Turku', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'oulu', name: 'Oulu', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'rovaniemi', name: 'Rovaniemi', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'jyvaskyla', name: 'Jyväskylä', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'kuopio', name: 'Kuopio', region: 'Finland', timezone: 'Europe/Helsinki' },
  { id: 'stockholm', name: 'Stockholm', region: 'Sweden', timezone: 'Europe/Stockholm' },
  { id: 'gothenburg', name: 'Gothenburg', region: 'Sweden', timezone: 'Europe/Stockholm' },
  { id: 'malmo', name: 'Malmö', region: 'Sweden', timezone: 'Europe/Stockholm' },
  { id: 'oslo', name: 'Oslo', region: 'Norway', timezone: 'Europe/Oslo' },
  { id: 'bergen', name: 'Bergen', region: 'Norway', timezone: 'Europe/Oslo' },
  { id: 'copenhagen', name: 'Copenhagen', region: 'Denmark', timezone: 'Europe/Copenhagen' },
  { id: 'aarhus', name: 'Aarhus', region: 'Denmark', timezone: 'Europe/Copenhagen' },
  { id: 'iceland', name: 'Reykjavik', region: 'Iceland', timezone: 'Atlantic/Reykjavik' },

  // --- EUROPE ---
  { id: 'london', name: 'London', region: 'UK', timezone: 'Europe/London' },
  { id: 'manchester', name: 'Manchester', region: 'UK', timezone: 'Europe/London' },
  { id: 'edinburgh', name: 'Edinburgh', region: 'UK', timezone: 'Europe/London' },
  { id: 'dublin', name: 'Dublin', region: 'Ireland', timezone: 'Europe/Dublin' },
  { id: 'paris', name: 'Paris', region: 'France', timezone: 'Europe/Paris' },
  { id: 'lyon', name: 'Lyon', region: 'France', timezone: 'Europe/Paris' },
  { id: 'nice', name: 'Nice', region: 'France', timezone: 'Europe/Paris' },
  { id: 'berlin', name: 'Berlin', region: 'Germany', timezone: 'Europe/Berlin' },
  { id: 'munich', name: 'Munich', region: 'Germany', timezone: 'Europe/Berlin' },
  { id: 'hamburg', name: 'Hamburg', region: 'Germany', timezone: 'Europe/Berlin' },
  { id: 'frankfurt', name: 'Frankfurt', region: 'Germany', timezone: 'Europe/Berlin' },
  { id: 'rome', name: 'Rome', region: 'Italy', timezone: 'Europe/Rome' },
  { id: 'milan', name: 'Milan', region: 'Italy', timezone: 'Europe/Rome' },
  { id: 'venice', name: 'Venice', region: 'Italy', timezone: 'Europe/Rome' },
  { id: 'naples', name: 'Naples', region: 'Italy', timezone: 'Europe/Rome' },
  { id: 'madrid', name: 'Madrid', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'barcelona', name: 'Barcelona', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'malaga', name: 'Málaga', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'alicante', name: 'Alicante', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'torrevieja', name: 'Torrevieja', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'palma', name: 'Palma de Mallorca', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'ibiza', name: 'Ibiza', region: 'Spain', timezone: 'Europe/Madrid' },
  { id: 'laspalmas', name: 'Las Palmas (Gran Canaria)', region: 'Spain', timezone: 'Atlantic/Canary' },
  { id: 'tenerife', name: 'Santa Cruz (Tenerife)', region: 'Spain', timezone: 'Atlantic/Canary' },
  { id: 'lisbon', name: 'Lisbon', region: 'Portugal', timezone: 'Europe/Lisbon' },
  { id: 'porto', name: 'Porto', region: 'Portugal', timezone: 'Europe/Lisbon' },
  { id: 'amsterdam', name: 'Amsterdam', region: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { id: 'rotterdam', name: 'Rotterdam', region: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { id: 'brussels', name: 'Brussels', region: 'Belgium', timezone: 'Europe/Brussels' },
  { id: 'vienna', name: 'Vienna', region: 'Austria', timezone: 'Europe/Vienna' },
  { id: 'zurich', name: 'Zurich', region: 'Switzerland', timezone: 'Europe/Zurich' },
  { id: 'geneva', name: 'Geneva', region: 'Switzerland', timezone: 'Europe/Zurich' },
  { id: 'prague', name: 'Prague', region: 'Czech Republic', timezone: 'Europe/Prague' },
  { id: 'budapest', name: 'Budapest', region: 'Hungary', timezone: 'Europe/Budapest' },
  { id: 'warsaw', name: 'Warsaw', region: 'Poland', timezone: 'Europe/Warsaw' },
  { id: 'krakow', name: 'Krakow', region: 'Poland', timezone: 'Europe/Warsaw' },
  { id: 'athens', name: 'Athens', region: 'Greece', timezone: 'Europe/Athens' },
  { id: 'rhodes', name: 'Rhodes', region: 'Greece', timezone: 'Europe/Athens' },
  { id: 'crete', name: 'Heraklion (Crete)', region: 'Greece', timezone: 'Europe/Athens' },
  { id: 'istanbul', name: 'Istanbul', region: 'Turkey', timezone: 'Europe/Istanbul' },
  { id: 'antalya', name: 'Antalya', region: 'Turkey', timezone: 'Europe/Istanbul' },
  { id: 'kyiv', name: 'Kyiv', region: 'Ukraine', timezone: 'Europe/Kyiv' },
  { id: 'moscow', name: 'Moscow', region: 'Russia', timezone: 'Europe/Moscow' },
  { id: 'stpetersburg', name: 'St. Petersburg', region: 'Russia', timezone: 'Europe/Moscow' },
  { id: 'tallinn', name: 'Tallinn', region: 'Estonia', timezone: 'Europe/Tallinn' },
  { id: 'riga', name: 'Riga', region: 'Latvia', timezone: 'Europe/Riga' },
  { id: 'vilnius', name: 'Vilnius', region: 'Lithuania', timezone: 'Europe/Vilnius' },
  { id: 'bucharest', name: 'Bucharest', region: 'Romania', timezone: 'Europe/Bucharest' },
  { id: 'sofia', name: 'Sofia', region: 'Bulgaria', timezone: 'Europe/Sofia' },
  { id: 'belgrade', name: 'Belgrade', region: 'Serbia', timezone: 'Europe/Belgrade' },
  { id: 'zagreb', name: 'Zagreb', region: 'Croatia', timezone: 'Europe/Zagreb' },
  { id: 'dubrovnik', name: 'Dubrovnik', region: 'Croatia', timezone: 'Europe/Zagreb' },
  { id: 'split', name: 'Split', region: 'Croatia', timezone: 'Europe/Zagreb' },

  // --- NORTH AMERICA ---
  { id: 'nyc', name: 'New York', region: 'USA', timezone: 'America/New_York' },
  { id: 'la', name: 'Los Angeles', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'chicago', name: 'Chicago', region: 'USA', timezone: 'America/Chicago' },
  { id: 'houston', name: 'Houston', region: 'USA', timezone: 'America/Chicago' },
  { id: 'phoenix', name: 'Phoenix', region: 'USA', timezone: 'America/Phoenix' },
  { id: 'philadelphia', name: 'Philadelphia', region: 'USA', timezone: 'America/New_York' },
  { id: 'sanantonio', name: 'San Antonio', region: 'USA', timezone: 'America/Chicago' },
  { id: 'sandiego', name: 'San Diego', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'dallas', name: 'Dallas', region: 'USA', timezone: 'America/Chicago' },
  { id: 'sanjose', name: 'San Jose', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'austin', name: 'Austin', region: 'USA', timezone: 'America/Chicago' },
  { id: 'jacksonville', name: 'Jacksonville', region: 'USA', timezone: 'America/New_York' },
  { id: 'sf', name: 'San Francisco', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'columbus', name: 'Columbus', region: 'USA', timezone: 'America/New_York' },
  { id: 'indianapolis', name: 'Indianapolis', region: 'USA', timezone: 'America/Indiana/Indianapolis' },
  { id: 'seattle', name: 'Seattle', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'denver', name: 'Denver', region: 'USA', timezone: 'America/Denver' },
  { id: 'dc', name: 'Washington D.C.', region: 'USA', timezone: 'America/New_York' },
  { id: 'boston', name: 'Boston', region: 'USA', timezone: 'America/New_York' },
  { id: 'nashville', name: 'Nashville', region: 'USA', timezone: 'America/Chicago' },
  { id: 'detroit', name: 'Detroit', region: 'USA', timezone: 'America/Detroit' },
  { id: 'portland', name: 'Portland', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'lasvegas', name: 'Las Vegas', region: 'USA', timezone: 'America/Los_Angeles' },
  { id: 'miami', name: 'Miami', region: 'USA', timezone: 'America/New_York' },
  { id: 'orlando', name: 'Orlando', region: 'USA', timezone: 'America/New_York' },
  { id: 'atlanta', name: 'Atlanta', region: 'USA', timezone: 'America/New_York' },
  { id: 'neworleans', name: 'New Orleans', region: 'USA', timezone: 'America/Chicago' },
  { id: 'hawaii', name: 'Honolulu', region: 'USA', timezone: 'Pacific/Honolulu' },
  { id: 'anchorage', name: 'Anchorage', region: 'USA', timezone: 'America/Anchorage' },
  { id: 'toronto', name: 'Toronto', region: 'Canada', timezone: 'America/Toronto' },
  { id: 'montreal', name: 'Montreal', region: 'Canada', timezone: 'America/Toronto' },
  { id: 'vancouver', name: 'Vancouver', region: 'Canada', timezone: 'America/Vancouver' },
  { id: 'calgary', name: 'Calgary', region: 'Canada', timezone: 'America/Edmonton' },
  { id: 'ottawa', name: 'Ottawa', region: 'Canada', timezone: 'America/Toronto' },
  { id: 'mexico', name: 'Mexico City', region: 'Mexico', timezone: 'America/Mexico_City' },
  { id: 'cancun', name: 'Cancun', region: 'Mexico', timezone: 'America/Cancun' },

  // --- SOUTH AMERICA ---
  { id: 'saopaulo', name: 'Sao Paulo', region: 'Brazil', timezone: 'America/Sao_Paulo' },
  { id: 'rio', name: 'Rio de Janeiro', region: 'Brazil', timezone: 'America/Sao_Paulo' },
  { id: 'buenosaires', name: 'Buenos Aires', region: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
  { id: 'santiago', name: 'Santiago', region: 'Chile', timezone: 'America/Santiago' },
  { id: 'bogota', name: 'Bogota', region: 'Colombia', timezone: 'America/Bogota' },
  { id: 'lima', name: 'Lima', region: 'Peru', timezone: 'America/Lima' },
  { id: 'caracas', name: 'Caracas', region: 'Venezuela', timezone: 'America/Caracas' },
  { id: 'quito', name: 'Quito', region: 'Ecuador', timezone: 'America/Guayaquil' },
  { id: 'montevideo', name: 'Montevideo', region: 'Uruguay', timezone: 'America/Montevideo' },
  { id: 'lapaz', name: 'La Paz', region: 'Bolivia', timezone: 'America/La_Paz' },

  // --- ASIA & MIDDLE EAST ---
  { id: 'tokyo', name: 'Tokyo', region: 'Japan', timezone: 'Asia/Tokyo' },
  { id: 'osaka', name: 'Osaka', region: 'Japan', timezone: 'Asia/Tokyo' },
  { id: 'kyoto', name: 'Kyoto', region: 'Japan', timezone: 'Asia/Tokyo' },
  { id: 'seoul', name: 'Seoul', region: 'South Korea', timezone: 'Asia/Seoul' },
  { id: 'busan', name: 'Busan', region: 'South Korea', timezone: 'Asia/Seoul' },
  { id: 'beijing', name: 'Beijing', region: 'China', timezone: 'Asia/Shanghai' },
  { id: 'shanghai', name: 'Shanghai', region: 'China', timezone: 'Asia/Shanghai' },
  { id: 'guangzhou', name: 'Guangzhou', region: 'China', timezone: 'Asia/Shanghai' },
  { id: 'shenzhen', name: 'Shenzhen', region: 'China', timezone: 'Asia/Shanghai' },
  { id: 'hongkong', name: 'Hong Kong', region: 'China', timezone: 'Asia/Hong_Kong' },
  { id: 'taipei', name: 'Taipei', region: 'Taiwan', timezone: 'Asia/Taipei' },
  { id: 'bangkok', name: 'Bangkok', region: 'Thailand', timezone: 'Asia/Bangkok' },
  { id: 'phuket', name: 'Phuket', region: 'Thailand', timezone: 'Asia/Bangkok' },
  { id: 'chiangmai', name: 'Chiang Mai', region: 'Thailand', timezone: 'Asia/Bangkok' },
  { id: 'hanoi', name: 'Hanoi', region: 'Vietnam', timezone: 'Asia/Bangkok' },
  { id: 'hochiminh', name: 'Ho Chi Minh City', region: 'Vietnam', timezone: 'Asia/Bangkok' },
  { id: 'phnompenh', name: 'Phnom Penh', region: 'Cambodia', timezone: 'Asia/Phnom_Penh' },
  { id: 'kualalumpur', name: 'Kuala Lumpur', region: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
  { id: 'singapore', name: 'Singapore', region: 'Singapore', timezone: 'Asia/Singapore' },
  { id: 'jakarta', name: 'Jakarta', region: 'Indonesia', timezone: 'Asia/Jakarta' },
  { id: 'bali', name: 'Bali (Denpasar)', region: 'Indonesia', timezone: 'Asia/Makassar' },
  { id: 'manila', name: 'Manila', region: 'Philippines', timezone: 'Asia/Manila' },
  { id: 'cebu', name: 'Cebu', region: 'Philippines', timezone: 'Asia/Manila' },
  { id: 'mumbai', name: 'Mumbai', region: 'India', timezone: 'Asia/Kolkata' },
  { id: 'delhi', name: 'New Delhi', region: 'India', timezone: 'Asia/Kolkata' },
  { id: 'bangalore', name: 'Bangalore', region: 'India', timezone: 'Asia/Kolkata' },
  { id: 'chennai', name: 'Chennai', region: 'India', timezone: 'Asia/Kolkata' },
  { id: 'kolkata', name: 'Kolkata', region: 'India', timezone: 'Asia/Kolkata' },
  { id: 'karachi', name: 'Karachi', region: 'Pakistan', timezone: 'Asia/Karachi' },
  { id: 'dhaka', name: 'Dhaka', region: 'Bangladesh', timezone: 'Asia/Dhaka' },
  { id: 'kathmandu', name: 'Kathmandu', region: 'Nepal', timezone: 'Asia/Kathmandu' },
  { id: 'dubai', name: 'Dubai', region: 'UAE', timezone: 'Asia/Dubai' },
  { id: 'abudhabi', name: 'Abu Dhabi', region: 'UAE', timezone: 'Asia/Dubai' },
  { id: 'doha', name: 'Doha', region: 'Qatar', timezone: 'Asia/Qatar' },
  { id: 'riyadh', name: 'Riyadh', region: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { id: 'jeddah', name: 'Jeddah', region: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { id: 'telaviv', name: 'Tel Aviv', region: 'Israel', timezone: 'Asia/Jerusalem' },
  { id: 'jerusalem', name: 'Jerusalem', region: 'Israel', timezone: 'Asia/Jerusalem' },
  { id: 'tehran', name: 'Tehran', region: 'Iran', timezone: 'Asia/Tehran' },
  { id: 'baghdad', name: 'Baghdad', region: 'Iraq', timezone: 'Asia/Baghdad' },

  // --- OCEANIA ---
  { id: 'sydney', name: 'Sydney', region: 'Australia', timezone: 'Australia/Sydney' },
  { id: 'melbourne', name: 'Melbourne', region: 'Australia', timezone: 'Australia/Melbourne' },
  { id: 'brisbane', name: 'Brisbane', region: 'Australia', timezone: 'Australia/Brisbane' },
  { id: 'perth', name: 'Perth', region: 'Australia', timezone: 'Australia/Perth' },
  { id: 'adelaide', name: 'Adelaide', region: 'Australia', timezone: 'Australia/Adelaide' },
  { id: 'canberra', name: 'Canberra', region: 'Australia', timezone: 'Australia/Sydney' },
  { id: 'hobart', name: 'Hobart', region: 'Australia', timezone: 'Australia/Hobart' },
  { id: 'darwin', name: 'Darwin', region: 'Australia', timezone: 'Australia/Darwin' },
  { id: 'auckland', name: 'Auckland', region: 'New Zealand', timezone: 'Pacific/Auckland' },
  { id: 'wellington', name: 'Wellington', region: 'New Zealand', timezone: 'Pacific/Auckland' },
  { id: 'christchurch', name: 'Christchurch', region: 'New Zealand', timezone: 'Pacific/Auckland' },
  { id: 'fiji', name: 'Fiji', region: 'Fiji', timezone: 'Pacific/Fiji' },

  // --- AFRICA ---
  { id: 'cairo', name: 'Cairo', region: 'Egypt', timezone: 'Africa/Cairo' },
  { id: 'lagos', name: 'Lagos', region: 'Nigeria', timezone: 'Africa/Lagos' },
  { id: 'nairobi', name: 'Nairobi', region: 'Kenya', timezone: 'Africa/Nairobi' },
  { id: 'capetown', name: 'Cape Town', region: 'South Africa', timezone: 'Africa/Johannesburg' },
  { id: 'johannesburg', name: 'Johannesburg', region: 'South Africa', timezone: 'Africa/Johannesburg' },
  { id: 'casablanca', name: 'Casablanca', region: 'Morocco', timezone: 'Africa/Casablanca' },
  { id: 'marrakech', name: 'Marrakech', region: 'Morocco', timezone: 'Africa/Casablanca' },
  { id: 'tunis', name: 'Tunis', region: 'Tunisia', timezone: 'Africa/Tunis' },
  { id: 'addisababa', name: 'Addis Ababa', region: 'Ethiopia', timezone: 'Africa/Addis_Ababa' },
  { id: 'accra', name: 'Accra', region: 'Ghana', timezone: 'Africa/Accra' },
];
